# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('batch', models.CharField(blank=True, max_length=300, null=True)),
                ('trader', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
